/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCutupsRouteImport } from './routes/app/cutups'
import { Route as AppExchangeRouteImport } from './routes/app/exchange'
import { Route as AppInsightsRouteImport } from './routes/app/insights'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppRosterRouteImport } from './routes/app/roster'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilmTagRouteImport } from './routes/api/film/tag'
import { Route as ApiSchoolUnlockRouteImport } from './routes/api/school/unlock'
import { Route as ApiShareCutupRouteImport } from './routes/api/share/cutup'
import { Route as ApiTeamMembersRouteImport } from './routes/api/team/members'
import { Route as AppCutupsCutupIdRouteImport } from './routes/app/cutups.$cutupId'
import { Route as AppFilmFilmIdRouteImport } from './routes/app/film.$filmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCutupsRoute = AppCutupsRouteImport.update({
  id: '/cutups',
  path: '/cutups',
  getParentRoute: () => AppRoute,
} as any)
const AppExchangeRoute = AppExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppRosterRoute = AppRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilmTagRoute = ApiFilmTagRouteImport.update({
  id: '/api/film/tag',
  path: '/api/film/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolUnlockRoute = ApiSchoolUnlockRouteImport.update({
  id: '/api/school/unlock',
  path: '/api/school/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareCutupRoute = ApiShareCutupRouteImport.update({
  id: '/api/share/cutup',
  path: '/api/share/cutup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamMembersRoute = ApiTeamMembersRouteImport.update({
  id: '/api/team/members',
  path: '/api/team/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCutupsCutupIdRoute = AppCutupsCutupIdRouteImport.update({
  id: '/$cutupId',
  path: '/$cutupId',
  getParentRoute: () => AppCutupsRoute,
} as any)
const AppFilmFilmIdRoute = AppFilmFilmIdRouteImport.update({
  id: '/film/$filmId',
  path: '/film/$filmId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/app/cutups': typeof AppCutupsRouteWithChildren
  '/app/exchange': typeof AppExchangeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/roster': typeof AppRosterRoute
  '/app/team': typeof AppTeamRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/film/tag': typeof ApiFilmTagRoute
  '/api/school/unlock': typeof ApiSchoolUnlockRoute
  '/api/share/cutup': typeof ApiShareCutupRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/app/cutups/$cutupId': typeof AppCutupsCutupIdRoute
  '/app/film/$filmId': typeof AppFilmFilmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/app/cutups': typeof AppCutupsRouteWithChildren
  '/app/exchange': typeof AppExchangeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/roster': typeof AppRosterRoute
  '/app/team': typeof AppTeamRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/film/tag': typeof ApiFilmTagRoute
  '/api/school/unlock': typeof ApiSchoolUnlockRoute
  '/api/share/cutup': typeof ApiShareCutupRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/app/cutups/$cutupId': typeof AppCutupsCutupIdRoute
  '/app/film/$filmId': typeof AppFilmFilmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/app/cutups': typeof AppCutupsRouteWithChildren
  '/app/exchange': typeof AppExchangeRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/library': typeof AppLibraryRoute
  '/app/roster': typeof AppRosterRoute
  '/app/team': typeof AppTeamRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/film/tag': typeof ApiFilmTagRoute
  '/api/school/unlock': typeof ApiSchoolUnlockRoute
  '/api/share/cutup': typeof ApiShareCutupRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/app/cutups/$cutupId': typeof AppCutupsCutupIdRoute
  '/app/film/$filmId': typeof AppFilmFilmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/join'
    | '/login'
    | '/parent'
    | '/api/health'
    | '/api/me'
    | '/app/cutups'
    | '/app/exchange'
    | '/app/insights'
    | '/app/library'
    | '/app/roster'
    | '/app/team'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/film/tag'
    | '/api/school/unlock'
    | '/api/share/cutup'
    | '/api/team/members'
    | '/app/cutups/$cutupId'
    | '/app/film/$filmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/login'
    | '/parent'
    | '/api/health'
    | '/api/me'
    | '/app/cutups'
    | '/app/exchange'
    | '/app/insights'
    | '/app/library'
    | '/app/roster'
    | '/app/team'
    | '/share/$token'
    | '/app'
    | '/api/auth/$'
    | '/api/film/tag'
    | '/api/school/unlock'
    | '/api/share/cutup'
    | '/api/team/members'
    | '/app/cutups/$cutupId'
    | '/app/film/$filmId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/join'
    | '/login'
    | '/parent'
    | '/api/health'
    | '/api/me'
    | '/app/cutups'
    | '/app/exchange'
    | '/app/insights'
    | '/app/library'
    | '/app/roster'
    | '/app/team'
    | '/share/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/film/tag'
    | '/api/school/unlock'
    | '/api/share/cutup'
    | '/api/team/members'
    | '/app/cutups/$cutupId'
    | '/app/film/$filmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeRoute: typeof ApiMeRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilmTagRoute: typeof ApiFilmTagRoute
  ApiSchoolUnlockRoute: typeof ApiSchoolUnlockRoute
  ApiShareCutupRoute: typeof ApiShareCutupRoute
  ApiTeamMembersRoute: typeof ApiTeamMembersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cutups': {
      id: '/app/cutups'
      path: '/cutups'
      fullPath: '/app/cutups'
      preLoaderRoute: typeof AppCutupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exchange': {
      id: '/app/exchange'
      path: '/exchange'
      fullPath: '/app/exchange'
      preLoaderRoute: typeof AppExchangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roster': {
      id: '/app/roster'
      path: '/roster'
      fullPath: '/app/roster'
      preLoaderRoute: typeof AppRosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/film/tag': {
      id: '/api/film/tag'
      path: '/api/film/tag'
      fullPath: '/api/film/tag'
      preLoaderRoute: typeof ApiFilmTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/school/unlock': {
      id: '/api/school/unlock'
      path: '/api/school/unlock'
      fullPath: '/api/school/unlock'
      preLoaderRoute: typeof ApiSchoolUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/cutup': {
      id: '/api/share/cutup'
      path: '/api/share/cutup'
      fullPath: '/api/share/cutup'
      preLoaderRoute: typeof ApiShareCutupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/members': {
      id: '/api/team/members'
      path: '/api/team/members'
      fullPath: '/api/team/members'
      preLoaderRoute: typeof ApiTeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cutups/$cutupId': {
      id: '/app/cutups/$cutupId'
      path: '/$cutupId'
      fullPath: '/app/cutups/$cutupId'
      preLoaderRoute: typeof AppCutupsCutupIdRouteImport
      parentRoute: typeof AppCutupsRoute
    }
    '/app/film/$filmId': {
      id: '/app/film/$filmId'
      path: '/film/$filmId'
      fullPath: '/app/film/$filmId'
      preLoaderRoute: typeof AppFilmFilmIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCutupsRouteChildren {
  AppCutupsCutupIdRoute: typeof AppCutupsCutupIdRoute
}

const AppCutupsRouteChildren: AppCutupsRouteChildren = {
  AppCutupsCutupIdRoute: AppCutupsCutupIdRoute,
}

const AppCutupsRouteWithChildren = AppCutupsRoute._addFileChildren(
  AppCutupsRouteChildren,
)

interface AppRouteChildren {
  AppCutupsRoute: typeof AppCutupsRouteWithChildren
  AppExchangeRoute: typeof AppExchangeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppRosterRoute: typeof AppRosterRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFilmFilmIdRoute: typeof AppFilmFilmIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCutupsRoute: AppCutupsRouteWithChildren,
  AppExchangeRoute: AppExchangeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppRosterRoute: AppRosterRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppFilmFilmIdRoute: AppFilmFilmIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeRoute: ApiMeRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilmTagRoute: ApiFilmTagRoute,
  ApiSchoolUnlockRoute: ApiSchoolUnlockRoute,
  ApiShareCutupRoute: ApiShareCutupRoute,
  ApiTeamMembersRoute: ApiTeamMembersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
